## Day 49 Lecture 1 Assignment

In this assignment, we will apply GMM (Gaussian Mixture Modeling) clustering to a dataset containing player-season statistics for NBA players from the past four years.

In [0]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.mixture import GaussianMixture
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from scipy.special import entr

This dataset contains player-season statistics for NBA players from the past four years. Each row in this dataset represents a player's per-game averages for a single season. 

This dataset contains the following variables:

- Seas: season ('2019' = 2018-2019 season, '2018' = 2017-2018 season, etc.)
- Player: player name
- Pos: position
- Age: age
- Tm: team
- G: games played
- GS: games started
- MP: minutes played
- FG: field goals
- FGA: field goals attempted
- FG%: field goal percentage
- 3P: 3 pointers
- 3PA: 3 pointers attempted
- 3P%: 3 point percentage
- 2P: 2 pointers
- 2PA: 2 pointers attempted
- 2P%: 2 point percentage
- eFG%: effective field goal percentage
- FT: free throws
- FTA: free throws attempted
- FT%: free throw percentage
- ORB: offensive rebound
- DRB: defensive rebound
- TRB: total rebounds
- AST: assists
- STL: steals
- BLK: blocks
- TOV: turnovers
- PF: personal fouls
- PTS: points

Load the dataset.

In [0]:
# answer goes here
df = pd.read_csv('https://raw.githubusercontent.com/qboy21/Thinkful/master/nba_player_seasons.csv')

The goal is to cluster these player-seasons to identify potential player "archetypes".  
The pre-processing steps will be identical to what we previously did for K-means.

Begin by removing players whose season did not meet one of the following criteria:
1. Started at least 20 games
2. Averaged at least 10 minutes per game

In [0]:
# answer goes here
df1 = df.loc[(df['GS'] >= 20) | (df['MP'] >= 10)]

Choose a subset of numeric columns that is interesting to you from an "archetypal" standpoint. 

We will choose the following basic statistics: **points, total rebounds, assists, steals, blocks**, and **turnovers**, but you should feel free to choose other reasonable feature sets if you like. Be careful not to include too many dimensions (curse of dimensionality).

In [0]:
# answer goes here
X = df1[['PTS','TRB','AST','STL','BLK','TOV']]

Standardize the features in your dataset using scikit-learn's StandardScaler, which will set the mean of each feature to 0 and the variance to 1.

In [0]:
# answer goes here
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

Run both K-Means and Gaussian mixtures modeling twice, once with 3 cluster and once with 7 clusters. Print out the resulting means for all 4 scenarios (KM+3, GMM+3, KM+7, GMM+7). When printing the means, transform the scaled versions back into their corresponding unscaled values. 

What "archetypes" do you see? Are the archetypes identified by GMM similar to those identified by K-Means? How do the means of GMM differ from those of K-Means?

In [96]:
# KM+3
kmeans_c = KMeans(n_clusters=3, random_state=123)
kmeans_c.fit(X_std)
centers = scaler.inverse_transform(kmeans_c.cluster_centers_)
centers_df = pd.DataFrame(centers, columns = ['Points', 'Rebounds', 'Assists', 'Steals', 'Blocks', 'Turnovers']) 
centers_df

      Points  Rebounds   Assists    Steals    Blocks  Turnovers
0  17.714643  4.648929  5.152500  1.222857  0.413571   2.496429
1   6.741087  2.844831  1.483512  0.549198  0.283957   0.871747
2  12.455249  7.190884  1.783978  0.827624  0.980110   1.485359

In [97]:
# GMM+3
# Defining the GMM clustering
gmm_cluster = GaussianMixture(n_components=3, random_state=123)

# Fit model
clusters = gmm_cluster.fit_predict(X_std)
# Scale GMM back to unscaled values
clusters_sc = scaler.inverse_transform(gmm_cluster.means_)
clusters_df = pd.DataFrame(clusters_sc, columns = ['Points', 'Rebounds', 'Assists', 'Steals', 'Blocks', 'Turnovers']) 
clusters_df

      Points  Rebounds  Assists    Steals    Blocks  Turnovers
0  13.142132  3.537871  3.91496  0.990146  0.288368   1.870360
1   6.304630  2.903495  1.17416  0.485438  0.290308   0.771833
2  11.886311  6.755539  1.80434  0.816966  0.940300   1.443301

In [98]:
# KM+7
kmeans_c = KMeans(n_clusters=7, random_state=123)
kmeans_c.fit(X_std)
centers = scaler.inverse_transform(kmeans_c.cluster_centers_)
centers_df = pd.DataFrame(centers, columns = ['Points', 'Rebounds', 'Assists', 'Steals', 'Blocks', 'Turnovers']) 
centers_df

      Points  Rebounds   Assists    Steals    Blocks  Turnovers
0   9.270079  2.883990  2.572703  0.829134  0.241207   1.262205
1  16.348023  3.859322  4.567232  1.083616  0.306215   2.248023
2   5.290265  2.315398  1.025133  0.410442  0.195929   0.666726
3  16.424000  9.780000  2.010667  0.818667  1.818667   1.960000
4  22.135897  6.633333  6.930769  1.583333  0.647436   3.273077
5  12.831776  6.872430  1.956542  0.919159  0.671495   1.486449
6   6.983577  4.689781  1.004015  0.500000  0.736496   0.871898

In [99]:
#GMM+7
# Defining the GMM clustering
gmm_cluster = GaussianMixture(n_components=7, random_state=123)

# Fit model
clusters = gmm_cluster.fit_predict(X_std)
# Scale GMM back to unscaled values
clusters_sc = scaler.inverse_transform(gmm_cluster.means_)
clusters_df = pd.DataFrame(clusters_sc, columns = ['Points', 'Rebounds', 'Assists', 'Steals', 'Blocks', 'Turnovers']) 
clusters_df

      Points  Rebounds   Assists    Steals    Blocks  Turnovers
0   7.975243  2.243152  2.553890  0.705717  0.173437   1.183424
1   5.959728  2.528754  0.974451  0.433829  0.203799   0.659009
2  11.303487  5.214333  1.917563  0.924056  0.498547   1.352957
3  16.981117  4.007774  4.943425  1.173012  0.317980   2.362020
4  15.204842  8.365654  2.389847  0.714854  1.360898   1.832695
5   6.172767  4.167677  0.855270  0.446073  0.622126   0.759276
6  20.336817  8.670385  6.637398  1.567287  1.002021   3.438537

Predict the likelihood of each season belonging to one of the 3 clusters using the GMM model. Then, calculate the entropy for each set of predicted probabilities. 

We will use entropy as a measure of how confident we are in the predicted class label. If we had no confidence in our prediction, we would assign 33% probability to each class, while if we were totally confident, we would assign 100% to one class. Entropy would be at a maximum in the "no confidence" scenario and a minimum in the "full confidence" scenario, which makes it a reasonable way to quantify our uncertainty in our prediction. There are certainly other methods as well; feel free to experiment with them if desired.

Which five predicted labels are we least confident about? Which five are we most confident about? Print out the associated details (season, player name, stats, etc.) from those seasons.

In [105]:
# GMM+3
gmm_cluster = GaussianMixture(n_components=3, random_state=123)

# Fit model
clusters = gmm_cluster.fit_predict(X_std)
# Scale GMM back to unscaled values
clusters_sc = scaler.inverse_transform(gmm_cluster.means_)
clusters_df = pd.DataFrame(clusters_sc, columns = ['Points', 'Rebounds', 'Assists', 'Steals', 'Blocks', 'Turnovers']) 
clusters_df
# Add column to DF
df1['cluster'] = clusters

# Predict 
df1['Predictions'] = clusters
df1['Probability'] = (gmm_cluster.predict_proba(X_std)).max(axis = 1)
# Calculate the Entropy
df1['Entropy'] = entr(df1['Probability'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [106]:
df1.groupby('Predictions')['Entropy'].mean().sort_values()

Predictions
2    0.070657
1    0.079556
0    0.084524
Name: Entropy, dtype: float64

In [104]:
df1

      Seas          Player Pos  ...  Predictions Probability   Entropy
0     2019    Álex Abrines  SG  ...            1    0.983117  0.016740
1     2019      Quincy Acy  PF  ...            1    0.990877  0.009081
2     2019    Jaylen Adams  PG  ...            1    0.952711  0.046153
3     2019    Steven Adams   C  ...            2    0.999983  0.000017
4     2019     Bam Adebayo   C  ...            2    0.958502  0.040625
...    ...             ...  ..  ...          ...         ...       ...
2134  2016     Tony Wroten  PG  ...            0    0.999984  0.000016
2137  2016      Nick Young  SG  ...            1    0.974611  0.025064
2138  2016  Thaddeus Young  PF  ...            2    0.999805  0.000195
2139  2016     Cody Zeller   C  ...            1    0.518177  0.340670
2140  2016    Tyler Zeller   C  ...            1    0.993419  0.006559

[1764 rows x 34 columns]